/**
 * lib/drug-info-extras.ts — Campos opcionales (signos_alarma, consejos_uso,
 * riesgo_beers, via, embarazo, lactancia, receta) por principio activo.
 *
 * Separado de drug-info.ts para evitar tocar las 380+ entries existentes.
 * El merge ocurre en lookupDrugInfo(); ver drug-info.ts.
 *
 * Cobertura: fármacos más usados en farmacia ambulatoria chilena para
 * adulto mayor. Faltantes simplemente no muestran las secciones extra.
 */

import type { DrugInfo } from './drug-info';

type Extras = Partial<Pick<DrugInfo,
  'signos_alarma' | 'consejos_uso' | 'riesgo_beers' | 'via' |
  'embarazo' | 'lactancia' | 'receta'
>>;

export const DRUG_EXTRAS: Record<string, Extras> = {
  PARACETAMOL: {
    signos_alarma: 'Coloración amarilla de piel u ojos, orina muy oscura, dolor en el costado derecho del abdomen, náuseas persistentes o sobredosis accidental. Acudir a urgencia.',
    consejos_uso: 'Puede tomarse con o sin alimentos. Espaciar al menos 6 horas entre dosis. Revisar siempre la composición de productos para resfrío: muchos contienen paracetamol y pueden sumar sin notarlo.',
    riesgo_beers: 'SEGURO',
    via: 'oral',
    embarazo: 'Considerado seguro en todos los trimestres bajo indicación. Analgésico de primera elección durante el embarazo.',
    lactancia: 'Compatible. Pasa en pequeñas cantidades a la leche sin efectos adversos descritos.',
    receta: 'venta_directa',
  },
  IBUPROFENO: {
    signos_alarma: 'Heces negras o con sangre, vómito con apariencia de café molido, dolor abdominal intenso, hinchazón de piernas, disminución importante de la orina, dolor en el pecho.',
    consejos_uso: 'Tomar siempre con alimentos o un vaso grande de agua para reducir molestias gástricas. No combinar con otros AINEs (diclofenaco, naproxeno, ketoprofeno). Espaciar al menos 8 horas entre dosis.',
    riesgo_beers: 'EVITAR',
    via: 'oral',
    embarazo: 'Evitar especialmente en el tercer trimestre (cierre del ductus arterioso, oligohidramnios). Solo bajo estricta indicación médica antes.',
    lactancia: 'Compatible en dosis ocasionales.',
    receta: 'venta_directa',
  },
  DICLOFENACO: {
    signos_alarma: 'Sangrado digestivo (heces negras, vómito sanguinolento), dolor en el pecho, falta de aire súbita, hinchazón de tobillos, disminución de orina, color amarillo de piel.',
    consejos_uso: 'Tomar con alimentos. La presentación en gel es preferible para dolor localizado en articulaciones o músculos: similar efecto local con mínima absorción sistémica.',
    riesgo_beers: 'EVITAR',
    via: 'oral',
    embarazo: 'Contraindicado en el tercer trimestre.',
    lactancia: 'Compatible en uso breve.',
    receta: 'venta_directa',
  },
  KETOROLACO: {
    signos_alarma: 'Disminución brusca de la orina, hinchazón, dolor abdominal, sangrado digestivo, dolor en el pecho. Suspender y acudir a urgencia.',
    consejos_uso: 'Uso máximo 5 días. Tomar con alimentos. Beber abundante agua. No combinar con otros AINEs.',
    riesgo_beers: 'EVITAR',
    via: 'oral',
    receta: 'simple',
  },
  NAPROXENO: {
    signos_alarma: 'Heces oscuras, vómito con sangre, dolor abdominal intenso, hinchazón, dolor en el pecho.',
    consejos_uso: 'Tomar con alimentos. Buena opción cuando se necesita un AINE de acción prolongada (12 horas). Mantener hidratación.',
    riesgo_beers: 'EVITAR',
    via: 'oral',
    receta: 'venta_directa',
  },
  METAMIZOL: {
    signos_alarma: 'Fiebre inexplicada, dolor de garganta, úlceras en la boca, palidez extrema, sangrado fácil, mareo intenso al ponerse de pie. Puede indicar agranulocitosis: acudir de inmediato a urgencia.',
    consejos_uso: 'Si está acostado, sentarse o pararse lentamente para evitar mareos por baja de presión. Puede oscurecer la orina (rojizo/rosado) sin gravedad.',
    riesgo_beers: 'PRECAUCION',
    via: 'oral',
    receta: 'venta_directa',
  },
  'ACIDO ACETILSALICILICO': {
    signos_alarma: 'Heces negras o con sangre, vómito tipo café molido, hematomas espontáneos, sangrado nasal o de encías persistente, zumbido de oídos, dificultad para respirar.',
    consejos_uso: 'Tomar con alimentos. La presentación con recubrimiento entérico se traga entera (no partir ni masticar). Avisar a su dentista o cirujano que la toma.',
    riesgo_beers: 'PRECAUCION',
    via: 'oral',
    embarazo: 'Dosis bajas pueden indicarse en algunos casos (preeclampsia). Dosis altas contraindicadas en tercer trimestre.',
    receta: 'venta_directa',
  },
  AMOXICILINA: {
    signos_alarma: 'Diarrea acuosa abundante o con sangre tras varios días de tratamiento (posible C. difficile), hinchazón de cara, lengua o garganta, dificultad para respirar, rash extenso con ampollas o fiebre.',
    consejos_uso: 'Completar TODO el tratamiento aunque mejore antes. Puede tomarse con o sin alimentos. Separar al menos 2 horas de antiácidos. Si toma anticonceptivos orales, use método de respaldo durante el tratamiento.',
    via: 'oral',
    embarazo: 'Compatible en todos los trimestres.',
    lactancia: 'Compatible.',
    receta: 'simple',
  },
  'AMOXICILINA + ACIDO CLAVULANICO': {
    signos_alarma: 'Diarrea con sangre o muy abundante, coloración amarilla de piel u ojos (hepatitis), rash con ampollas, fiebre alta.',
    consejos_uso: 'Tomar al inicio de la comida para reducir diarrea y náuseas. Completar todo el tratamiento.',
    via: 'oral',
    receta: 'simple',
  },
  AZITROMICINA: {
    signos_alarma: 'Palpitaciones, mareo intenso, desmayo, latidos irregulares, dolor en el pecho. Diarrea con sangre.',
    consejos_uso: 'Tomar siempre a la misma hora. Separar al menos 2 horas de antiácidos con aluminio o magnesio. Si tiene cardiopatía, avise al médico antes de iniciar.',
    riesgo_beers: 'PRECAUCION',
    via: 'oral',
    receta: 'simple',
  },
  CIPROFLOXACINO: {
    signos_alarma: 'Dolor súbito en talón, tobillo, hombro o muñeca (riesgo de ruptura tendinosa), hormigueo o adormecimiento de manos o pies, confusión, alucinaciones, palpitaciones, diarrea con sangre, hipoglucemia.',
    consejos_uso: 'Beber abundante agua. Separar 2 horas de lácteos, antiácidos, hierro, calcio o magnesio. Evitar exposición solar prolongada. Suspender ante cualquier dolor tendinoso y consultar.',
    riesgo_beers: 'EVITAR',
    via: 'oral',
    embarazo: 'Contraindicado.',
    receta: 'simple',
  },
  METRONIDAZOL: {
    signos_alarma: 'Adormecimiento u hormigueo en manos o pies, convulsiones, confusión, lengua negra, orina muy oscura.',
    consejos_uso: 'NO consumir alcohol durante el tratamiento ni hasta 48 horas después (puede causar reacción severa: rubor, vómitos, palpitaciones). Tomar con alimentos. Puede dar sabor metálico.',
    via: 'oral',
    receta: 'simple',
  },
  LOSARTAN: {
    signos_alarma: 'Hinchazón de cara, labios o lengua, mareo intenso al ponerse de pie, disminución importante de la orina, palpitaciones, calambres musculares.',
    consejos_uso: 'Tomar siempre a la misma hora. Levantarse lentamente para evitar mareo. Evitar sustitutos de la sal (suelen contener potasio). Controlar presión arterial en casa al menos 2 veces por semana.',
    riesgo_beers: 'PRECAUCION',
    via: 'oral',
    embarazo: 'Contraindicado en todos los trimestres.',
    receta: 'simple',
  },
  ENALAPRIL: {
    signos_alarma: 'Hinchazón de cara, labios o lengua (angioedema, urgencia), tos seca persistente, mareo al ponerse de pie, disminución de orina.',
    consejos_uso: 'Tomar a la misma hora cada día. Levantarse lentamente. Evitar sustitutos de la sal. Si aparece tos seca persistente, consultar para evaluar cambio a un ARA II (losartán).',
    riesgo_beers: 'PRECAUCION',
    via: 'oral',
    embarazo: 'Contraindicado.',
    receta: 'simple',
  },
  AMLODIPINO: {
    signos_alarma: 'Dolor en el pecho que empeora al iniciar el tratamiento, hinchazón intensa de tobillos, palpitaciones rápidas, mareo o desmayo.',
    consejos_uso: 'Puede causar hinchazón leve de tobillos (frecuente, no grave). Tomar a la misma hora. Evitar pomelo (toronja) que aumenta sus niveles.',
    riesgo_beers: 'SEGURO',
    via: 'oral',
    receta: 'simple',
  },
  ATENOLOL: {
    signos_alarma: 'Pulso muy lento (<50/min), falta de aire, hinchazón de piernas, mareo, manos y pies muy fríos.',
    consejos_uso: 'NO suspender abruptamente: debe reducirse gradualmente bajo indicación. Si es diabético, vigilar glicemia (puede enmascarar bajadas).',
    riesgo_beers: 'PRECAUCION',
    via: 'oral',
    receta: 'simple',
  },
  HIDROCLOROTIAZIDA: {
    signos_alarma: 'Calambres frecuentes, debilidad muscular, mareo intenso, palpitaciones, gota aguda, orina muy escasa.',
    consejos_uso: 'Tomar por la mañana para evitar levantarse a orinar en la noche. Mantener buena hidratación. Controles de potasio y función renal periódicos.',
    riesgo_beers: 'PRECAUCION',
    via: 'oral',
    receta: 'simple',
  },
  ATORVASTATINA: {
    signos_alarma: 'Dolor muscular intenso o generalizado, debilidad muscular, orina color té o cola (rabdomiólisis), coloración amarilla de piel u ojos.',
    consejos_uso: 'Puede tomarse a cualquier hora, idealmente en la noche. Evitar el pomelo (toronja). Control de enzimas hepáticas y CK si hay molestias musculares.',
    riesgo_beers: 'SEGURO',
    via: 'oral',
    embarazo: 'Contraindicado.',
    receta: 'simple',
  },
  SIMVASTATINA: {
    signos_alarma: 'Dolor muscular intenso, debilidad, orina color té (rabdomiólisis), coloración amarilla de piel.',
    consejos_uso: 'Tomar en la noche (mayor síntesis hepática de colesterol nocturna). Evitar pomelo. No combinar con dosis altas de amiodarona, verapamilo o diltiazem sin ajuste.',
    riesgo_beers: 'SEGURO',
    via: 'oral',
    receta: 'simple',
  },
  METFORMINA: {
    signos_alarma: 'Náuseas y vómitos persistentes, dolor muscular generalizado, respiración rápida y profunda, dolor abdominal intenso, somnolencia inusual (riesgo de acidosis láctica). Suspender ante deshidratación, vómitos o diarrea importantes.',
    consejos_uso: 'Tomar SIEMPRE con alimentos (reduce molestias digestivas). Iniciar con dosis baja e ir subiendo. Suspender 48 horas antes y después de exámenes con contraste yodado.',
    riesgo_beers: 'PRECAUCION',
    via: 'oral',
    embarazo: 'Compatible bajo indicación.',
    receta: 'simple',
  },
  LEVOTIROXINA: {
    signos_alarma: 'Palpitaciones, temblor, pérdida de peso rápida, insomnio, dolor en el pecho (exceso de dosis). Aumento de peso, cansancio extremo, intolerancia al frío (falta de dosis).',
    consejos_uso: 'Tomar EN AYUNAS, 30–60 minutos antes del desayuno, con agua. Separar al menos 4 horas de calcio, hierro, antiácidos, omeprazol y soya (reducen absorción). Mismo horario y misma marca siempre.',
    riesgo_beers: 'PRECAUCION',
    via: 'oral',
    embarazo: 'Compatible y necesaria; suele requerir aumento de dosis.',
    receta: 'simple',
  },
  OMEPRAZOL: {
    signos_alarma: 'Diarrea persistente o con sangre, calambres frecuentes, fracturas espontáneas, palpitaciones, dificultad para tragar nueva, pérdida de peso inexplicada, vómito con sangre.',
    consejos_uso: 'Tomar 30–60 minutos antes del desayuno, con agua, cápsula entera. No usar más de 8 semanas seguidas sin reevaluar con su médico. Separar de levotiroxina al menos 4 horas.',
    riesgo_beers: 'PRECAUCION',
    via: 'oral',
    receta: 'venta_directa',
  },
  ESOMEPRAZOL: {
    signos_alarma: 'Diarrea persistente, calambres, fracturas espontáneas, dificultad para tragar nueva, pérdida de peso, vómito con sangre.',
    consejos_uso: 'Tomar 30–60 minutos antes de la comida principal. No usar crónicamente sin reevaluación médica.',
    riesgo_beers: 'PRECAUCION',
    via: 'oral',
    receta: 'venta_directa',
  },
  SALBUTAMOL: {
    signos_alarma: 'Empeoramiento de la falta de aire después de usarlo, palpitaciones intensas, dolor en el pecho, temblor severo, necesidad de usar el inhalador más de 4 veces al día.',
    consejos_uso: 'Agitar el inhalador antes. Exhalar, sellar boquilla con labios, presionar e inspirar lento y profundo, mantener aire 10 segundos. Enjuagar la boca después. Si lo usa con espaciador (aerocámara), mejor depósito pulmonar.',
    via: 'inhalatoria',
    receta: 'venta_directa',
  },
  LORATADINA: {
    consejos_uso: 'Una sola dosis al día, con o sin alimentos. Causa menos somnolencia que clorfenamina. Buena opción para adulto mayor con alergia.',
    riesgo_beers: 'SEGURO',
    via: 'oral',
    receta: 'venta_directa',
  },
  CETIRIZINA: {
    consejos_uso: 'Una vez al día, idealmente en la noche por leve somnolencia que puede dar. Reducir dosis en insuficiencia renal.',
    riesgo_beers: 'PRECAUCION',
    via: 'oral',
    receta: 'venta_directa',
  },
  CLORFENAMINA: {
    signos_alarma: 'Confusión, dificultad para orinar, palpitaciones, agitación, caídas. Suspender y consultar.',
    consejos_uso: 'En adulto mayor preferir loratadina o bilastina (menos sedantes y anticolinérgicas). Si se usa, evitar conducir.',
    riesgo_beers: 'EVITAR',
    via: 'oral',
    receta: 'venta_directa',
  },
  PSEUDOEFEDRINA: {
    signos_alarma: 'Palpitaciones, dolor en el pecho, dolor de cabeza intenso, mareo, presión arterial elevada, insomnio.',
    consejos_uso: 'Evitar tomarlo en la noche (insomnio). No usar si tiene hipertensión, glaucoma, hipertrofia prostática o cardiopatía.',
    riesgo_beers: 'EVITAR',
    via: 'oral',
    receta: 'venta_directa',
  },
  WARFARINA: {
    signos_alarma: 'Sangrado de encías, nasal o por la orina, heces negras, vómito con sangre, hematomas espontáneos, dolor de cabeza intenso o súbito, debilidad de un lado del cuerpo.',
    consejos_uso: 'Mantener consumo estable de verduras de hoja verde (no eliminarlas, pero sin cambios bruscos). Avisar a TODOS los profesionales que la toma. Controles de INR según indicación.',
    riesgo_beers: 'PRECAUCION',
    via: 'oral',
    receta: 'retenida',
  },
  CLOPIDOGREL: {
    signos_alarma: 'Sangrado prolongado, heces negras, hematomas espontáneos, manchas rojizas en la piel, debilidad súbita de un lado del cuerpo.',
    consejos_uso: 'Tomar a la misma hora cada día. Suspender 5–7 días antes de cirugía solo si lo indica el cardiólogo. Avisar a su dentista.',
    via: 'oral',
    receta: 'simple',
  },
  ALPRAZOLAM: {
    signos_alarma: 'Somnolencia diurna excesiva, confusión, caídas, dificultad para respirar (especialmente combinado con alcohol u opioides).',
    consejos_uso: 'Uso corto (semanas, no meses). No suspender abruptamente: debe reducirse gradualmente. No conducir. NO combinar con alcohol.',
    riesgo_beers: 'EVITAR',
    via: 'oral',
    receta: 'retenida',
  },
  CLONAZEPAM: {
    signos_alarma: 'Somnolencia excesiva, confusión, caídas, problemas de memoria, depresión respiratoria.',
    consejos_uso: 'NO suspender abruptamente. No conducir. Evitar alcohol. En adulto mayor preferir otras alternativas para ansiedad o insomnio.',
    riesgo_beers: 'EVITAR',
    via: 'oral',
    receta: 'retenida',
  },
  TRAMADOL: {
    signos_alarma: 'Convulsiones, confusión, agitación, alucinaciones, sudoración profusa, temblor (síndrome serotoninérgico), depresión respiratoria.',
    consejos_uso: 'Iniciar con dosis baja en adulto mayor. Mantener buena hidratación y fibra para prevenir constipación. Evitar combinar con antidepresivos sin supervisión médica.',
    riesgo_beers: 'PRECAUCION',
    via: 'oral',
    receta: 'retenida',
  },
  PREDNISONA: {
    signos_alarma: 'Heces negras, dolor abdominal intenso, hiperglicemia (mucha sed, mucha orina), hinchazón importante, cambios bruscos de ánimo, infecciones que se agravan rápido.',
    consejos_uso: 'Tomar en la mañana con desayuno (imita ritmo natural del cortisol). No suspender abruptamente tratamientos prolongados: debe disminuirse gradualmente.',
    riesgo_beers: 'PRECAUCION',
    via: 'oral',
    receta: 'simple',
  },
  'VITAMINA D3': {
    consejos_uso: 'Tomar con la comida más grasa del día (mejora absorción). Indicada para mantener salud ósea, especialmente en adulto mayor. Controles de calcio si se usan dosis altas (>2000 UI/día).',
    riesgo_beers: 'SEGURO',
    via: 'oral',
    embarazo: 'Compatible y recomendada bajo indicación.',
    lactancia: 'Compatible.',
    receta: 'venta_directa',
  },
  CIANOCOBALAMINA: {
    consejos_uso: 'Útil en deficiencias por dieta o malabsorción (gastritis atrófica, uso prolongado de omeprazol o metformina). Vía intramuscular en deficiencias severas.',
    riesgo_beers: 'SEGURO',
    via: 'oral',
    receta: 'venta_directa',
  },
  'VITAMINA C': {
    consejos_uso: 'Con o sin alimentos. Dosis altas (>1 g/día) pueden causar diarrea o cálculos renales en personas susceptibles.',
    riesgo_beers: 'SEGURO',
    via: 'oral',
    receta: 'venta_directa',
  },
  HIERRO: {
    signos_alarma: 'Vómitos, dolor abdominal intenso, heces negras (esperable por el hierro, pero distinguir de sangrado), confusión.',
    consejos_uso: 'Tomar en ayunas con vitamina C (jugo de naranja) para mejor absorción. Si causa molestias gástricas, tomar con comida. Separar 2 horas de calcio, antiácidos, lácteos, café y té.',
    via: 'oral',
    receta: 'venta_directa',
  },
  CALCIO: {
    consejos_uso: 'Repartir dosis a lo largo del día (máximo 500 mg por toma para mejor absorción). Tomar con alimentos si es carbonato. Mantener actividad física y vitamina D adecuada.',
    riesgo_beers: 'SEGURO',
    via: 'oral',
    receta: 'venta_directa',
  },
  MAGNESIO: {
    consejos_uso: 'Útil para calambres y constipación. Reducir dosis si causa diarrea. Precaución en insuficiencia renal.',
    riesgo_beers: 'PRECAUCION',
    via: 'oral',
    receta: 'venta_directa',
  },
  SILDENAFIL: {
    signos_alarma: 'Dolor en el pecho, mareo intenso, pérdida súbita de visión o audición, erección dolorosa de más de 4 horas. Suspender y acudir a urgencia.',
    consejos_uso: 'NO combinar con nitratos (riesgo de baja de presión grave). Tomar 30–60 min antes. Evitar comidas muy grasas (reducen absorción).',
    via: 'oral',
    receta: 'simple',
  },
  TADALAFILO: {
    signos_alarma: 'Dolor en el pecho, mareo, pérdida súbita de visión o audición, erección de más de 4 horas.',
    consejos_uso: 'NO combinar con nitratos. Inicio más lento pero efecto hasta 36 horas.',
    via: 'oral',
    receta: 'simple',
  },
  TAMSULOSINA: {
    signos_alarma: 'Mareo intenso o desmayo al ponerse de pie, palpitaciones, erección dolorosa prolongada.',
    consejos_uso: 'Tomar siempre 30 min después de la misma comida. La primera dosis al acostarse para evitar caídas por mareo. Avisar al oftalmólogo (síndrome iris flácido en cirugía de catarata).',
    riesgo_beers: 'PRECAUCION',
    via: 'oral',
    receta: 'simple',
  },
  FINASTERIDA: {
    consejos_uso: 'Tomar a la misma hora cada día. Efectos sobre síntomas prostáticos toman 3–6 meses. Las mujeres embarazadas NO deben manipular comprimidos partidos.',
    via: 'oral',
    receta: 'simple',
  },
  ESCITALOPRAM: {
    signos_alarma: 'Pensamientos de hacerse daño (especialmente al inicio), agitación, palpitaciones, temblor, sudoración, confusión, calambres, debilidad (hiponatremia, frecuente en adulto mayor).',
    consejos_uso: 'Efecto pleno toma 4–6 semanas. NO suspender abruptamente (riesgo de síndrome de discontinuación). Tomar a la misma hora. Vigilar sodio en sangre en adulto mayor.',
    riesgo_beers: 'PRECAUCION',
    via: 'oral',
    receta: 'simple',
  },
  SERTRALINA: {
    signos_alarma: 'Pensamientos suicidas (especialmente al inicio), agitación, hiponatremia (debilidad, confusión), sangrado fácil, palpitaciones.',
    consejos_uso: 'Tomar con alimentos para mejor absorción. Mismo horario diario. NO suspender abruptamente. Efecto pleno en 4–6 semanas.',
    riesgo_beers: 'PRECAUCION',
    via: 'oral',
    receta: 'simple',
  },
  GABAPENTINA: {
    signos_alarma: 'Somnolencia excesiva, mareo, hinchazón de piernas, dificultad para respirar, ideas suicidas.',
    consejos_uso: 'Subir y bajar dosis siempre gradualmente. Separar 2 horas de antiácidos. En adulto mayor con insuficiencia renal ajustar dosis (alta acumulación).',
    riesgo_beers: 'PRECAUCION',
    via: 'oral',
    receta: 'simple',
  },
  PREGABALINA: {
    signos_alarma: 'Somnolencia, mareo, hinchazón, aumento de peso, dificultad para respirar, confusión, ideas suicidas.',
    consejos_uso: 'Subir y bajar dosis siempre gradualmente. Puede causar dependencia.',
    riesgo_beers: 'PRECAUCION',
    via: 'oral',
    receta: 'retenida',
  },
  ZOPICLONA: {
    signos_alarma: 'Caídas, confusión nocturna, problemas de memoria, comportamientos automáticos (sonambulismo), somnolencia diurna.',
    consejos_uso: 'Solo uso corto (no más de 2–4 semanas). Tomar justo antes de acostarse. NO conducir al día siguiente si queda somnoliento.',
    riesgo_beers: 'EVITAR',
    via: 'oral',
    receta: 'retenida',
  },
  ZOLPIDEM: {
    signos_alarma: 'Caídas nocturnas, confusión, sonambulismo, conducción dormida, alucinaciones.',
    consejos_uso: 'Tomar acostado, justo antes de dormir, con al menos 7–8 h disponibles. No combinar con alcohol. Uso corto.',
    riesgo_beers: 'EVITAR',
    via: 'oral',
    receta: 'retenida',
  },
  DIAZEPAM: {
    signos_alarma: 'Caídas, confusión, somnolencia diurna, depresión respiratoria, problemas de memoria.',
    consejos_uso: 'No suspender abruptamente. Evitar alcohol. En adulto mayor preferir alternativas no benzodiacepínicas.',
    riesgo_beers: 'EVITAR',
    via: 'oral',
    receta: 'retenida',
  },
  LORAZEPAM: {
    signos_alarma: 'Caídas, sedación excesiva, confusión, depresión respiratoria con opioides.',
    consejos_uso: 'Uso corto. Reducir gradualmente. No combinar con alcohol u opioides sin supervisión.',
    riesgo_beers: 'EVITAR',
    via: 'oral',
    receta: 'retenida',
  },
  HALOPERIDOL: {
    signos_alarma: 'Rigidez muscular, fiebre, sudoración, confusión (síndrome neuroléptico maligno), movimientos involuntarios, palpitaciones.',
    consejos_uso: 'No es recomendable como sedante para insomnio o delirium leve en adulto mayor. Solo bajo indicación psiquiátrica.',
    riesgo_beers: 'EVITAR',
    via: 'oral',
    receta: 'retenida',
  },
  QUETIAPINA: {
    signos_alarma: 'Mareo intenso al ponerse de pie, palpitaciones, fiebre con rigidez, movimientos involuntarios, hiperglicemia, somnolencia extrema.',
    consejos_uso: 'Iniciar con dosis baja. Tomar en la noche. Levantarse lentamente. Vigilar glicemia y peso.',
    riesgo_beers: 'EVITAR',
    via: 'oral',
    receta: 'retenida',
  },
  AMITRIPTILINA: {
    signos_alarma: 'Confusión, retención de orina, palpitaciones, caídas, boca seca extrema, estreñimiento severo.',
    consejos_uso: 'En adulto mayor preferir alternativas con menos efectos anticolinérgicos. Tomar en la noche por sedación.',
    riesgo_beers: 'EVITAR',
    via: 'oral',
    receta: 'simple',
  },
  FLUOXETINA: {
    signos_alarma: 'Ideas suicidas (al inicio), agitación, palpitaciones, sangrado fácil, debilidad y confusión (hiponatremia).',
    consejos_uso: 'Vida media muy larga: efectos y reacciones tardan en aparecer y desaparecer. Tomar en la mañana (puede dar insomnio).',
    riesgo_beers: 'PRECAUCION',
    via: 'oral',
    receta: 'simple',
  },
  VENLAFAXINA: {
    signos_alarma: 'Hipertensión, sudoración profusa, palpitaciones, agitación, ideas suicidas al inicio, síntomas de discontinuación al saltar dosis (mareo, sensación eléctrica).',
    consejos_uso: 'Tomar con alimentos. Mismo horario diario. NUNCA suspender abruptamente. Controlar presión arterial.',
    riesgo_beers: 'PRECAUCION',
    via: 'oral',
    receta: 'simple',
  },
  CARBAMAZEPINA: {
    signos_alarma: 'Rash con ampollas o descamación (síndrome de Stevens-Johnson, urgencia), fiebre, dolor de garganta, hematomas, coloración amarilla de piel, debilidad y confusión (hiponatremia).',
    consejos_uso: 'Tomar con alimentos. No suspender abruptamente. Controles de hemograma, sodio y función hepática.',
    riesgo_beers: 'PRECAUCION',
    via: 'oral',
    receta: 'simple',
  },
  FENITOINA: {
    signos_alarma: 'Marcha inestable, doble visión, confusión, rash extenso, sangrado de encías, hipertrofia de encías.',
    consejos_uso: 'Tomar con alimentos. Higiene dental rigurosa. No cambiar de marca sin avisar al médico.',
    riesgo_beers: 'PRECAUCION',
    via: 'oral',
    receta: 'simple',
  },
  LEVETIRACETAM: {
    signos_alarma: 'Cambios de ánimo bruscos, agitación, ideas suicidas, somnolencia excesiva.',
    consejos_uso: 'Tomar a la misma hora cada día. No suspender abruptamente.',
    via: 'oral',
    receta: 'simple',
  },
  LEVODOPA: {
    signos_alarma: 'Movimientos involuntarios nuevos, alucinaciones, caídas por baja de presión al ponerse de pie, confusión.',
    consejos_uso: 'Tomar 30 min antes o 1–2 h después de comidas ricas en proteínas (compiten por absorción). No suspender abruptamente.',
    riesgo_beers: 'PRECAUCION',
    via: 'oral',
    receta: 'simple',
  },
  DONEPEZILO: {
    signos_alarma: 'Pulso lento o desmayo, vómitos persistentes, pérdida de peso importante, calambres musculares.',
    consejos_uso: 'Tomar en la noche. Iniciar con dosis baja para reducir molestias digestivas. Evaluar respuesta a los 3 meses.',
    via: 'oral',
    receta: 'simple',
  },
  MEMANTINA: {
    consejos_uso: 'Subir dosis gradualmente. Tomar a la misma hora. Ajustar en insuficiencia renal.',
    via: 'oral',
    receta: 'simple',
  },
  FUROSEMIDA: {
    signos_alarma: 'Mareo intenso, calambres, debilidad muscular, palpitaciones, deshidratación, disminución brusca de orina.',
    consejos_uso: 'Tomar por la mañana. Pesarse a diario en igualdad de condiciones. Controlar potasio y función renal.',
    riesgo_beers: 'PRECAUCION',
    via: 'oral',
    receta: 'simple',
  },
  ESPIRONOLACTONA: {
    signos_alarma: 'Palpitaciones, debilidad muscular, hormigueo (hipercalemia), disminución de la orina, ginecomastia dolorosa.',
    consejos_uso: 'Tomar con alimentos. Evitar sustitutos de la sal. Controles de potasio y función renal.',
    riesgo_beers: 'PRECAUCION',
    via: 'oral',
    receta: 'simple',
  },
  DIGOXINA: {
    signos_alarma: 'Náuseas, vómitos, visión amarillenta o borrosa, palpitaciones lentas o irregulares, confusión. Pueden indicar intoxicación, suspender y consultar.',
    consejos_uso: 'Tomar a la misma hora. Mantener nivel estable de potasio. Avisar al médico si vomita o tiene diarrea importante (riesgo de intoxicación).',
    riesgo_beers: 'PRECAUCION',
    via: 'oral',
    receta: 'simple',
  },
  RIVAROXABAN: {
    signos_alarma: 'Sangrado de encías o nariz prolongado, heces negras, orina rojiza, hematomas espontáneos, dolor de cabeza intenso súbito, debilidad de un lado.',
    consejos_uso: 'Dosis ≥15 mg: tomar SIEMPRE con alimentos. Si olvida una dosis, NO duplicar. Avisar a TODOS los profesionales.',
    riesgo_beers: 'PRECAUCION',
    via: 'oral',
    receta: 'retenida',
  },
  APIXABAN: {
    signos_alarma: 'Sangrado prolongado, heces negras, orina con sangre, hematomas espontáneos, dolor de cabeza súbito intenso.',
    consejos_uso: 'Tomar 2 veces al día a horas regulares, con o sin alimentos. No duplicar dosis si olvida.',
    via: 'oral',
    receta: 'retenida',
  },
  DABIGATRAN: {
    signos_alarma: 'Sangrado, heces negras, vómito con sangre, dolor abdominal intenso, dolor de cabeza súbito.',
    consejos_uso: 'Tragar entera la cápsula, no abrir ni masticar. Conservar en envase original (sensible a humedad).',
    via: 'oral',
    receta: 'retenida',
  },
  INSULINA: {
    signos_alarma: 'Sudoración fría, temblor, palpitaciones, confusión, mareo (hipoglucemia). Tener glucosa o azúcar a mano.',
    consejos_uso: 'Rotar sitios de inyección. Conservar refrigerada hasta abrir (no congelar). Comprobar fecha de vencimiento.',
    via: 'inyectable',
    embarazo: 'Compatible y necesaria en gestantes con diabetes.',
    receta: 'simple',
  },
  GLIBENCLAMIDA: {
    signos_alarma: 'Sudoración, temblor, confusión, mareo (hipoglucemia, puede ser prolongada y grave en adulto mayor).',
    consejos_uso: 'Tomar 30 min antes del desayuno. NO saltarse comidas. Tener glucosa a mano.',
    riesgo_beers: 'EVITAR',
    via: 'oral',
    receta: 'simple',
  },
  GLIMEPIRIDA: {
    signos_alarma: 'Hipoglucemia (sudor, temblor, confusión), especialmente en adulto mayor o tras saltarse comidas.',
    consejos_uso: 'Tomar con el desayuno. No saltarse comidas.',
    riesgo_beers: 'PRECAUCION',
    via: 'oral',
    receta: 'simple',
  },
  EMPAGLIFLOZINA: {
    signos_alarma: 'Sed intensa, mucha orina, mareo, infección urinaria, infección genital, dolor en zona genital o perineal (riesgo bajo pero grave: gangrena de Fournier).',
    consejos_uso: 'Buena hidratación. Higiene genital cuidadosa. Suspender 3 días antes de cirugías mayores.',
    via: 'oral',
    receta: 'simple',
  },
  LEVOFLOXACINO: {
    signos_alarma: 'Dolor súbito en talón u hombro (riesgo ruptura tendón), hormigueo, confusión, palpitaciones, diarrea con sangre.',
    consejos_uso: 'Beber abundante agua. Separar 2 h de antiácidos, hierro, calcio, lácteos. Evitar sol. Suspender ante dolor tendinoso.',
    riesgo_beers: 'EVITAR',
    via: 'oral',
    receta: 'simple',
  },
  CEFALEXINA: {
    signos_alarma: 'Diarrea acuosa o con sangre persistente, rash extenso, hinchazón de cara o lengua.',
    consejos_uso: 'Completar todo el tratamiento. Con o sin alimentos.',
    via: 'oral',
    receta: 'simple',
  },
  CLARITROMICINA: {
    signos_alarma: 'Palpitaciones, mareo intenso, color amarillo de piel, diarrea con sangre.',
    consejos_uso: 'Completar tratamiento. Avisar de TODOS los medicamentos: tiene muchas interacciones (estatinas, anticoagulantes, etc.).',
    riesgo_beers: 'PRECAUCION',
    via: 'oral',
    receta: 'simple',
  },
  NITROFURANTOINA: {
    signos_alarma: 'Falta de aire, tos seca persistente (toxicidad pulmonar), hormigueo, color amarillo de piel.',
    consejos_uso: 'Tomar con alimentos. No usar en insuficiencia renal moderada-severa (frecuente en adulto mayor).',
    riesgo_beers: 'EVITAR',
    via: 'oral',
    receta: 'simple',
  },
  COTRIMOXAZOL: {
    signos_alarma: 'Rash con ampollas (Stevens-Johnson), fiebre, palpitaciones, debilidad, hematomas.',
    consejos_uso: 'Beber abundante agua. Vigilar potasio (puede subir) y función renal en adulto mayor.',
    riesgo_beers: 'PRECAUCION',
    via: 'oral',
    receta: 'simple',
  },
  ACICLOVIR: {
    signos_alarma: 'Confusión, alucinaciones, temblor, disminución de la orina (especialmente en adulto mayor con función renal limítrofe).',
    consejos_uso: 'Beber abundante agua. Iniciar al primer síntoma de herpes (hormigueo, ardor). Ajustar dosis si insuficiencia renal.',
    via: 'oral',
    receta: 'simple',
  },
  FLUCONAZOL: {
    signos_alarma: 'Color amarillo de piel u ojos, dolor abdominal intenso, rash con ampollas, palpitaciones.',
    consejos_uso: 'Avisar de TODOS los medicamentos: interactúa con estatinas, warfarina, sulfonilureas.',
    via: 'oral',
    receta: 'simple',
  },
  PREDNISOLONA: {
    signos_alarma: 'Heces negras, dolor abdominal, hiperglicemia, hinchazón, cambios de ánimo, infecciones que se agravan.',
    consejos_uso: 'Tomar en la mañana con desayuno. No suspender abruptamente tratamientos prolongados.',
    riesgo_beers: 'PRECAUCION',
    via: 'oral',
    receta: 'simple',
  },
  BUDESONIDA: {
    signos_alarma: 'Empeoramiento brusco del asma o EPOC, infecciones respiratorias frecuentes, candidiasis oral.',
    consejos_uso: 'Inhalar lento y profundo. Enjuagar la boca y escupir después de cada uso (prevenir candidiasis). Usar espaciador si está disponible.',
    via: 'inhalatoria',
    receta: 'simple',
  },
  MONTELUKAST: {
    signos_alarma: 'Cambios de ánimo, ansiedad, ideas suicidas, pesadillas, agresividad. Consultar si aparecen.',
    consejos_uso: 'Tomar en la noche, con o sin alimentos.',
    via: 'oral',
    receta: 'simple',
  },
  BILASTINA: {
    consejos_uso: 'Tomar en ayunas: separar al menos 1 h antes o 2 h después de comidas y jugos de fruta (reducen absorción).',
    riesgo_beers: 'SEGURO',
    via: 'oral',
    receta: 'venta_directa',
  },
  FEXOFENADINA: {
    consejos_uso: 'Mejor con agua, no con jugos de fruta (reducen absorción). Causa muy poca somnolencia.',
    riesgo_beers: 'SEGURO',
    via: 'oral',
    receta: 'venta_directa',
  },
  DOMPERIDONA: {
    signos_alarma: 'Palpitaciones, mareo intenso, desmayo.',
    consejos_uso: 'Tomar 15–30 min antes de las comidas. Uso corto (≤7 días). No usar si tiene cardiopatía o QT largo.',
    riesgo_beers: 'PRECAUCION',
    via: 'oral',
    receta: 'simple',
  },
  METOCLOPRAMIDA: {
    signos_alarma: 'Movimientos involuntarios de cara o lengua (pueden ser permanentes), inquietud extrema, rigidez muscular.',
    consejos_uso: 'Uso máximo 5 días. NO usar en adulto mayor de forma prolongada.',
    riesgo_beers: 'EVITAR',
    via: 'oral',
    receta: 'simple',
  },
  ONDANSETRON: {
    signos_alarma: 'Palpitaciones, mareo, desmayo, estreñimiento severo.',
    consejos_uso: 'Disolver en la lengua (presentación dispersable) sin agua. Útil para náuseas por quimioterapia o postoperatorio.',
    via: 'oral',
    receta: 'simple',
  },
  LOPERAMIDA: {
    signos_alarma: 'Distensión abdominal severa, ausencia de gases o heces, palpitaciones (a dosis altas).',
    consejos_uso: 'NO usar si hay fiebre alta, diarrea con sangre o sospecha de infección bacteriana. Hidratarse bien.',
    via: 'oral',
    receta: 'venta_directa',
  },
  LACTULOSA: {
    consejos_uso: 'Beber abundante agua. Efecto en 24–48 h. Puede dar distensión y gases al inicio. Reducir dosis si causa diarrea.',
    riesgo_beers: 'SEGURO',
    via: 'oral',
    receta: 'venta_directa',
  },
  MACROGOL: {
    consejos_uso: 'Disolver en vaso de agua. Beber abundante líquido durante el día. Buena opción de primera línea para constipación crónica en adulto mayor.',
    riesgo_beers: 'SEGURO',
    via: 'oral',
    receta: 'venta_directa',
  },
  OXIBUTININA: {
    signos_alarma: 'Confusión, retención de orina, boca seca extrema, estreñimiento severo, caídas, visión borrosa.',
    consejos_uso: 'En adulto mayor preferir alternativas (mirabegrón, trospio) por menor riesgo anticolinérgico cerebral.',
    riesgo_beers: 'EVITAR',
    via: 'oral',
    receta: 'simple',
  },
  ESCOPOLAMINA: {
    signos_alarma: 'Visión borrosa, boca seca extrema, retención de orina, confusión, palpitaciones.',
    consejos_uso: 'Uso corto para cólicos. En adulto mayor con cuidado por efectos anticolinérgicos.',
    riesgo_beers: 'PRECAUCION',
    via: 'oral',
    receta: 'simple',
  },
  ALOPURINOL: {
    signos_alarma: 'Rash con ampollas o descamación (Stevens-Johnson, urgencia), fiebre, ganglios inflamados, color amarillo de piel.',
    consejos_uso: 'Iniciar con dosis baja. Beber abundante agua. NO iniciar durante una crisis aguda de gota.',
    via: 'oral',
    receta: 'simple',
  },
  COLCHICINA: {
    signos_alarma: 'Diarrea importante (signo precoz de toxicidad, suspender), dolor muscular, debilidad, sangrado fácil. Margen terapéutico estrecho.',
    consejos_uso: 'Reducir dosis en insuficiencia renal o hepática. Avisar de TODOS los medicamentos (interactúa con estatinas, claritromicina).',
    riesgo_beers: 'PRECAUCION',
    via: 'oral',
    receta: 'simple',
  },
};
